server:
  port: 8088

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 平台服务转发
        - id: api-platform
          uri: http://localhost:8081
          predicates:
            - Path=/yunapi/**
          filters:
            - StripPrefix=0
            - name: AuthKey
              args:
                enable: false
            - name: ApiRequestLog
              args:
                enable: false
        # 动态转发至后端服务
        - id: open-service1
          uri: http://localhost:8081
          predicates:
            - Path=/openapi/**
          filters:
            - RewritePath=/openapi/(?<segment>.*), /yunapi/openapi/$\{segment}
            - name: AuthKey
              args:
                enable: true
            - name: ApiRequestLog
              args:
                enable: true
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 5   # 每秒新增 5 个令牌
                redis-rate-limiter.burstCapacity: 10  # 最大令牌桶容量
                key-resolver: "#{@ipKeyResolver}"
  data:
    redis:
      database: 1
      host: localhost
      port: 6379
      client-type: lettuce
      lettuce:
        pool:
          max-active: 500
          max-wait: -1
          max-idle: 50
          min-idle: 100
          time-between-eviction-runs: 180000

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: read_only

logging:
  level:
    org.springframework.cloud.gateway: debug
    reactor.netty: info

dubbo:
  application:
    name: gateway-service
    qos-enable: false
  registry:
    address: zookeeper://127.0.0.1:2181  # 连接注册中心
    register: false
  consumer:
    check: true
#    generic: true