server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        # 动态转发至后端服务1
        - id: open-service1
          uri: http://localhost:8081/openapi
          predicates:
            - Path=/openapi/**
          filters:
            - StripPrefix=1
        # 动态转发至后端服务2
#        - id: open-service2
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/order/**
#          filters:
#            - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  endpoint:
    gateway:
      access: read_only

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG