spring:
  application:
    name: yun-api-platform
  datasource:
    url: jdbc:postgresql://localhost:5432/api-platform-dev
    driver-class-name: org.postgresql.Driver
    username: qianfang
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 10000
server:
  port: 8081
  servlet:
    context-path: /openapi
# 日志配置
logging:
  level:
    com.qfleaf: debug
# mybatis-plus配置
mybatis-plus:
  global-config:
    db-config:
      id-type: ASSIGN_ID
      logic-delete-field: deletedAt      # 逻辑删除字段
      logic-delete-value: now()          # 逻辑删除时的值
      logic-not-delete-value: 'null'     # 未删除的值
# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
    version: openapi_3_1
  group-configs:
    - group: 'a-default'
      display-name: "默认"
      paths-to-match: '/**'
      packages-to-scan: com.qfleaf.yunapi.controller
  cache:
    disabled: true
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: false
  setting:
    language: zh_cn
    swagger-model-name: 实体模型